services:
  db:
    image: postgres
    container_name: portfolio_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-portfolio:/var/lib/postgresql/data
    restart: always

  portfolio:
    build: .
    container_name: portfolio_app
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE}
      IMAGE_PATH: ${IMAGE_PATH}
    volumes:
      - ./uploads:/portfolio_spring_app/${IMAGE_PATH}
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "portfolio.jar"]
    restart: always