services:
  db:
    image: postgres
    container_name: portfolio_db
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_PASSWORD=db4lif3
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-portfolio:/var/lib/postgresql/data
    restart: always

  portfolio:
    build: .
    container_name: portfolio_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "portfolio.jar"]
    restart: always

