services:
  db:
    ports:
      - "5432:5432"
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=postgres
    volumes:
      - /your-folder-path:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: backend_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_name
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=db_password
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "portfolio.jar"]
    restart: always

